# Docker Compose untuk Self-Hosting ML Forecast App - SIMPLIFIED VERSION
version: '3.8'

services:
  ml-forecast-app:
    build:
      context: .
      dockerfile: Dockerfile.selfhost
    container_name: ml-forecast-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - FORECAST_N_JOBS=2
      - FORECAST_PROGRESS=1
      - FORECAST_DEBUG=0
      - MAX_DATA_ROWS=1000000
      - MAX_DATA_MONTHS=12
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static
    networks:
      - ml-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ml-network:
    driver: bridge
